print("I'm Krishma Adhikari.")
print("I'm from Nuwakot.")
print("My favourite hobby is writing codes.")
print("I love reading books as well.")
print("I love to watch animies.")
print("I love Kanha and RadhaRani.")
print("I believe in \"jo hota hai achhe k liye hota hai\"")
print("I want to go to the mountains.")
print("I love Lumle.")
print("I love my family.")